server:
  port: 8081

spring:
  application:
    name: kafka-streams-producer

  cloud:
    stream:
      kafka:
        binder:
          brokers: 172.16.97.52:7092
      poller:
        fixedDelay: 50
      bindings:
        moneySupplier-out-0:
          destination: kafka-stream-topic
        streams:
          binder:
            deserializationExceptionHandler: sendToDlq
            configuration:
              commit.interval.ms: 100
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.springframework.kafka.support.serializer.JsonSerde




